### ISSUE TITLE
Test dependency on `generics-sop` needs upper bound (or arbitrary instances need updating)

### ISSUE THREAD

**Issue by mdorman** [Soostone/uri-bytestring#50]
The package states that it depends on `generics-sop >= 0.2`, but attempts to compile with `generics-sop-0.4.0.1` results in:

```
Building test suite 'test' for uri-bytestring-0.3.2.1..
[1 of 4] Compiling URI.ByteString.Arbitrary ( test/URI/ByteString/Arbitrary.hs, dist/build/test/test-tmp/URI/ByteString/Arbitrary.o )

test/URI/ByteString/Arbitrary.hs:42:28: error:
    • Could not deduce (SOP.All SOP.SListI xs)
        arising from a use of ‘SOP.hsequence’
      from the context: (SOP.SListI xs, SOP.AllF (SOP.All Arbitrary) xs,
                         SOP.AllF SOP.SListI xs)
        bound by the type signature for:
                   sopArbitrary' :: forall (xs :: [[*]]).
                                    (SOP.SListI xs, SOP.AllF (SOP.All Arbitrary) xs,
                                     SOP.AllF SOP.SListI xs) =>
                                    Gen (SOP.SOP SOP.I xs)
        at test/URI/ByteString/Arbitrary.hs:(39,1)-(41,27)
    • In the first argument of ‘map’, namely ‘SOP.hsequence’
      In the expression: map SOP.hsequence
      In the first argument of ‘oneof’, namely
        ‘(map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)’
   |
42 | sopArbitrary' = oneof (map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)
   |                            ^^^^^^^^^^^^^

test/URI/ByteString/Arbitrary.hs:42:61: error:
    • Could not deduce (SOP.All (SOP.All Arbitrary) xs)
        arising from a use of ‘SOP.hcpure’
      from the context: (SOP.SListI xs, SOP.AllF (SOP.All Arbitrary) xs,
                         SOP.AllF SOP.SListI xs)
        bound by the type signature for:
                   sopArbitrary' :: forall (xs :: [[*]]).
                                    (SOP.SListI xs, SOP.AllF (SOP.All Arbitrary) xs,
                                     SOP.AllF SOP.SListI xs) =>
                                    Gen (SOP.SOP SOP.I xs)
        at test/URI/ByteString/Arbitrary.hs:(39,1)-(41,27)
    • In the second argument of ‘($)’, namely ‘SOP.hcpure p arbitrary’
      In the second argument of ‘($)’, namely
        ‘SOP.apInjs_POP $ SOP.hcpure p arbitrary’
      In the first argument of ‘oneof’, namely
        ‘(map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)’
   |
42 | sopArbitrary' = oneof (map SOP.hsequence $ SOP.apInjs_POP $ SOP.hcpure p arbitrary)
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^
[2 of 4] Compiling URI.ByteStringQQTests ( test/URI/ByteStringQQTests.hs, dist/build/test/test-tmp/URI/ByteStringQQTests.o )
```
